query GetDoctorBySlug($slug: String!) {
  personnel(where: {_or: [{slug: {_eq: $slug}}, {slug_en: {_eq: $slug}}]}) {
    id
    name
    name_en
    description
    description_en
    image
    slug
    slug_en
    experience
    experience_en
    seo_title
    seo_description
    seo_title_en
    seo_description_en
    certificates
    image_alt
    image_alt_en
    personnel_services {
      service {
        id
        name
        name_en
        slug
        slug_en
        image
      }
    }
    categories {
      category {
        title_en
        title
        slug
        id
      }
    }
  }
}
