query GetPriceList {
  price_list_categories {
    title
    title_en
    slug
    id
    price_list_items {
      id
      price
      title
    }
  }
}

query GetPriceListCategories {
  price_list_categories {
    title
    title_en
    slug
    id
  }
}


query GetPriceListCategoryById {
  price_list {
    price
    id
    title
  }
}
