  query GetServices {
    services(
      where: {
        parent_id: { _is_null: true }
        _or: [{ is_geo_page: { _eq: false } }, { is_geo_page: { _is_null: true } }]
      }
      order_by: { created_at: asc }
    ) {
      id
      name
      name_en
      description
      description_en
      mainImage
      slug
      slug_en
      image
      parent_id
      is_geo_page
      seo_title
      seo_description
      seo_title_en
      seo_description_en
      created_at
      child_services(order_by: { created_at: asc }) {
        id
        name
        name_en
        slug
        slug_en
        image
        parent_id
        is_geo_page
      }
    }
  }

query GetServiceBySlug($slug: String!) {
  services(where: {_or: [{slug: {_eq: $slug}}, {slug_en: {_eq: $slug}}]}) {
    id
    name
    name_en
    slug
    slug_en
    image
    mainImage
    description
    description_en
    seo_title
    seo_description
    seo_title_en
    seo_description_en
    created_at
    parent_id
    is_geo_page
    custom_robots
    faq_ua
    faq_en
    parent_service {
      id
      name
      name_en
      slug
      slug_en
    }
    child_services(order_by: {created_at: asc}) {
      id
      name
      name_en
      slug
      slug_en
      image
    }
    personnel_services {
      personnel {
        name_en
        name
        id
        image
        description
        description_en
        categories {
          category {
            title
            title_en
            id
          }
        }
        slug_en
        slug
      }
    }
    image_alt
    image_alt_en
  }
}
