query GetServices {
  services(order_by: {created_at: asc}) {
    id
    name
    name_en
    slug      
    slug_en     
    image
    seo_title
    seo_description
    seo_title_en
    seo_description_en
    created_at
  }
}


query GetServiceBySlug($slug: String!) {
  services(where: {
    _or: [
      { slug: { _eq: $slug } },
      { slug_en: { _eq: $slug } }
    ]
  }) {
    id
    name
    name_en
    slug        
    slug_en 
    image
    mainImage
    description
    seo_title
    seo_description
    seo_title_en
    seo_description_en
    created_at
  }
}